In [1]:
import random
import numpy as np

In [2]:
def sign(x, theta_value):
    t = []
    for i in range(len(x)):
        tem = x[i] - theta_value
        if tem > 0:
            t.append(1)
        else :
            t.append(-1)
    return np.array(t)

In [3]:
def generate_data(size, noise):
    x = np.zeros((size, 1))
    y = np.zeros((size, 1))
    for i in range(size):
        x[i][0] = random.uniform(-1,1)
        ran = random.uniform(0,1)
        if ran < noise:
            y[i][0] = -sign(x[i],0.0)
        else:
            y[i][0] = sign(x[i],0.0)
    return x, y
generate_data(2,0)



(array([[ 0.5332097 ],
        [-0.02979184]]),
 array([[ 1.],
        [-1.]]))

In [4]:
def get_theta(x,size):
    
    tem = np.sort(x[:,0])
    theta = np.zeros((size,1))
    for i in range(size-1):
        theta[i] = (tem[i]+tem[i+1])/2
    theta[-1] = -1
    #theta[0] = -1
    return theta
x, y = generate_data(2,0)
get_theta(x,2)


array([[-0.14899683],
       [-1.        ]])

In [5]:
def decision_stump(size, noise):
    e_in = np.zeros((2,size-1))
    x, y = generate_data(size, noise)
    theta = get_theta(x, size)
    for i in range(len(theta)):
        dif = y[:,0]*sign(x[:,0],theta[i])
        e_in[0][i] = (size - np.sum(dif))/ 2 / size
        e_in[1][i] = (size - np.sum(-dif))/ 2 / size
    err_pos, err_neg = np.min(e_in[0]), np.min(e_in[1])
    #print(err_pos, err_neg)
    best_theta = 0
    if err_pos < err_neg:
        s = 1
        best_theta =  theta[np.argmin(e_in[0]),0]
        return err_pos, best_theta, s
    else:
        s = -1
        best_theta =  theta[np.argmin(e_in[1]),0]
        return err_neg, best_theta, s
        
                
            
        

In [ ]:
def decision_stump1(size, noise):
    e_in = 1
    x, y = generate_data(size, noise)
    theta = get_theta(x, size)
    for i in theta[:,0]:
        dif_pos = np.where(x[:,0]>i,1,-1)
        dif_neg = np.where(x[:,0]<i,1,-1)
        err_pos = sum(dif_pos != y[:,0])
        err_neg = sum(dif_neg != y[:,0])
        #print(err_pos, err_neg)
        err_pos /= size
        err_neg /= size
        if err_pos > err_neg:
            if e_in > err_neg:
                e_in = err_neg
                s = -1
                best_theta = i
        else:
            if e_in > err_pos:
                e_in = err_pos
                s = 1
                best_theta = i
        #print(e_in)
    return e_in, best_theta, s
    
decision_stump1(2,0)        

In [ ]:
def problem(size,noise):
    sum_ein = 0
    sum_eout = 0
    for i in range(10000):
        e_in, best_theta, s = decision_stump1(size, noise)
        sum_ein += e_in
        if s == 1:
            sum_eout += abs(best_theta)/2 * (1 - noise) + noise * (1 - abs(best_theta)/2)
        else:
            sum_eout += abs(best_theta)/2 * (noise) + (1 - noise) * (1 - abs(best_theta)/2)
        #sum_eout += 0.5+0.3*s*(abs(best_theta)-1)
    return sum_ein/10000, sum_eout/10000,  sum_eout/10000 -sum_ein/10000

In [ ]:
problem(200,0.1)

In [ ]:
x = np.array([1,-12,1])
y = np.array([-1])
z = np.array([-1,-1,-1])
np.sign(x-y)*z

In [ ]:
x= []
x.append(1)
x.append(1)
x

In [ ]:
dif = np.array([1,-1,1])
size = 3
(size - np.sum(-dif))/ 2 / size

In [ ]:
size = 2
noise = 0
x, y = generate_data(size, noise)
theta = get_theta(x, size)
dif_pos = sign(x[:,0],theta[1])
dif_neg = -sign(x[:,0],theta[1])
err_pos = sum(dif_pos != y[0])
err_neg = sum(dif_neg != y)[0]
print(dif_neg,dif_pos)
print(y)
print(err_neg,err_pos)