In [21]:
import random 
import numpy as np
import math
import sys
def sign(x):
    if x <= 0:
        return -1
    
    else : 
        return 1
x = []
for i in  range(0,20):
    x.append([random.random()*2-1])
noise = 0

for i in range(0,20):
    ran = random.random()
    #print(ran)
    if ran <= 0.2:
        noise+=1
        x[i].append(-sign(x[i][0]))
    else :x[i].append(sign(x[i][0]))
#print("noise:",noise)
x = np.array(x)

In [10]:
def decision_stump(dataset):

    sort_d = sorted(dataset)
    min_pos = []

    err = 0

    min_err = len(dataset)

    for i in range(0,len(dataset)+1):
        for k in range(0,i):
            if sort_d[k][1]>0:
                err+=1
        for k in range(i,len(dataset)):
            if sort_d[k][1]<0:
                err+=1
        if err < min_err:
            min_pos = []
            min_pos.append(i)
            min_err = err
        elif err == min_err:
            min_pos.append(i)
        err = 0
# choose the lowest Ein randomly
    choosen = int(len(min_pos)*random.random())
    if min_pos[choosen] < len(sort_d):
        return [sort_d[min_pos[choosen]][0],min_err]
    else: return [(sort_d[min_pos[choosen]-1][0]+1)/2,min_err]
    

In [11]:
decision_stump(x)

[-0.7165971541528073, 6]

In [22]:
y = [(x[i]+x[i+1])/2 for i in range(0, x.shape[0]-1)]
y

[array([-0.50378339, -1.        ]),
 array([0.1237912, 0.       ]),
 array([0.59389223, 1.        ]),
 array([0.0508444, 0.       ]),
 array([-0.29842315,  0.        ]),
 array([0.02177121, 0.        ]),
 array([-0.07370201,  0.        ]),
 array([-0.24306188,  0.        ]),
 array([0.0796598, 0.       ]),
 array([0.00022394, 0.        ]),
 array([-0.26198719, -1.        ]),
 array([-0.00601972,  0.        ]),
 array([0.16632011, 0.        ]),
 array([ 0.42540687, -1.        ]),
 array([ 0.19245411, -1.        ]),
 array([0.11906189, 0.        ]),
 array([0.28270387, 1.        ]),
 array([-0.00296948,  1.        ]),
 array([0.51751152, 1.        ])]

In [25]:
x.shape[0]

20

In [111]:
import numpy as np
import random
class decisonStump(object):
    def __init__(self,dimension,data_count,noise):
        self.dimension=dimension
        self.data_count=data_count
        self.noise=noise
    def generate_dataset(self):
        dataset=np.zeros((self.data_count,self.dimension+1))
        for i in range(self.data_count):
            x=random.uniform(-1,1)
            line=[]
            line.append(x)
            y=np.sign(x)*np.sign(random.uniform(0,1)-self.noise)
            line.append(y)
            dataset[i:]=line
        #print(dataset)
        return dataset
    def get_theta(self,dataset):
        l=np.sort(dataset[:,0])
        theta=np.zeros((self.data_count,1))
        for i in range(self.data_count-1):
            theta[i]=(l[i]+l[i+1])/2
        theta[-1]=1
        #print(len(theta))
        return theta
    def question1718(self):
        sum_e_in = 0
        sum_e_out=0
        for i in range(5000):
            dataset = self.generate_dataset()
            #print(len(dataset))
            theta=self.get_theta(dataset)
            #print(theta)
            e_in = np.zeros((2, self.data_count))
            for j in range(self.data_count):
                a=dataset[:,1]*np.sign(dataset[:,0]-theta[j])
                #print(dataset[:,0])
                e_in[0][j] = (self.data_count - np.sum(a)) / (2 * self.data_count)  # 陣列只有-1和+1，可直接計算出-1所佔比例
                e_in[1][j] = (self.data_count - np.sum(-a)) / (2 * self.data_count)
            min0, min1 = np.min(e_in[0]), np.min(e_in[1])
            s=0
            theta_best=0
            if min0 < min1:
                s = 1
                theta_best = theta[np.argmin(e_in[0]),0]
                #print(theta_best,'----')
                sum_e_in+=min0
            else:
                s = -1
               # print(np.argmin(e_in[1]),'+++++++')
                theta_best = theta[np.argmin(e_in[1]),0]
               # print(theta_best)
                sum_e_in+=min1
            e_out=1 - abs(theta_best)
            sum_e_out+=e_out
        print(sum_e_in/5000,sum_e_out/5000)


if __name__=='__main__':
    decision=decisonStump(1,20,0)
    decision.question1718()

0.0 0.9518393109565011


In [110]:
import sys
import numpy as np
import math
from random import *

# generate input data with 20% flipping noise
def generate_input_data(time_seed):
    np.random.seed(time_seed)
    raw_X = np.sort(np.random.uniform(-1,1,2))
    noised_y = np.sign(raw_X)*np.where(np.random.random(raw_X.shape[0])<0,-1,1)
    return raw_X, noised_y

def calculate_Ein(x,y):
    # calculate median of interval & negative infinite & positive infinite
    thetas = np.array( [float("-inf")]+[ (x[i]+x[i+1])/2 for i in range(0, x.shape[0]-1) ]+[float("inf")] )
    Ein = x.shape[0]
    sign = 1
    target_theta = 0.0
    # positive and negative rays
    for theta in thetas:
        y_positive = np.where(x>theta,1,-1)
        y_negative = np.where(x<theta,1,-1)
#         print(y_negative)
#         print(y)
        error_positive = sum(y_positive!=y)
        error_negative = sum(y_negative!=y)
        #print(error_negative)
        if error_positive>error_negative:
            if Ein>error_negative:
                Ein = error_negative
                sign = -1
                target_theta = theta
        else:
            if Ein>error_positive:
                Ein = error_positive
                sign = 1
                target_theta = theta
    # two corner cases
    if target_theta==float("inf"):
        target_theta = 1.0
    if target_theta==float("-inf"):
        target_theta = -1.0
    return Ein, target_theta, sign


if __name__ == '__main__':
    T = 1000
    total_Ein = 0
    sum_Eout = 0
    for i in range(0,T):
        x,y = generate_input_data(i)
        curr_Ein, theta, sign = calculate_Ein(x,y)
        total_Ein = total_Ein + curr_Ein
        sum_Eout = sum_Eout + 0.5+0.3*sign*(abs(theta)-1)
    print ((total_Ein*1.0) / (T*2))
    print ((sum_Eout*1.0) / T)

0.0
0.375127441680704


In [4]:
e = 1
while True:
    tem = 10 ** e - 1
    if tem % 17 == 0:
        print(e)
        break
    else:
        e += 1

16
